### ISSUE TITLE
Retrieved Date-format in resolver incorrect

### ISSUE THREAD

**Issue by bsandmann** [hyperledger-labs/did-webs-resolver#27]
I was trying out the version of the webs universal resolver hosted [here](https://dev.uniresolver.io/)

The resolution metadata result looked like this:
`{
  "retrieved": "2023-11-01T14:18:06.601278+00:00",
  ...
  }`
 The date-format is not quite as expected and defined [in the DID core spec](https://www.w3.org/TR/did-core/#did-document-metadata)
 
 Maybe it's already fixed. Just wanted to let you know :)

**Comment by 2byrds** [comment]
Thank you @bsandmann we'll update that soon

**Comment by 2byrds** [comment]
PR submitted here https://github.com/hyperledger-labs/did-webs-resolver/pull/28

**Comment by 2byrds** [comment]
I went ahead and merged this.
