### ISSUE TITLE
Failing to run  dkr did webs service due to KeyError: 'keri.cesr.dir'

### ISSUE THREAD

**Issue by jruizaranguren** [hyperledger-labs/did-webs-resolver#36]
In order to test did.webs resolution, I'm executing the following steps (trying to avoid witnesses burden):

```bash
export CONFIG_ROOT=$(pwd)/.keri
export SOMEDID_SALT="$(kli salt)"

mkdir -p ${CONFIG_ROOT}/somedid

echo "Creating somedid config..."
echo '{
    "transferable": true,
    "wits": [],
    "toad": 0,
    "icount": 1,
    "ncount": 1,
    "isith": "1",
    "nsith": "1"}' > ${CONFIG_ROOT}/somedid/somedid_aid_config.json

echo "Creating somedid keystore..."
kli init --name somedid --salt ${SOMEDID_SALT} --nopasscode \
    --base ${CONFIG_ROOT} \
    --config-dir ${CONFIG_ROOT}
echo ""
echo "Creating somedid identifier..."
kli incept --name somedid \
    --alias somedid \
    --base ${CONFIG_ROOT} \
    -f ${CONFIG_ROOT}/somedid/somedid_aid_config.json

echo "Creating did for somedid..."
prefix="$(kli did generate --name somedid \
    --base ${CONFIG_ROOT} | awk -F':' '{print $NF}')"

echo "Generating did:webs for somedid..."
dkr did webs generate --name somedid \
    --did did:webs:danubetech.com:example:"$prefix" --base ${CONFIG_ROOT}
```

This results in the creation of two files at `$(PWD)`, not related to $`{CONFIG_ROOT}`:

* ./did_json/{prefix}/did.json
* ./keri_cesr/{prefix}/keri.cesr

Now, when I try to run the service through:

` dkr did webs service -p 8080 -n somedid --base ${CONFIG_ROOT} `

I get the following error:

```bash
  File "/my/pathj/to/.venv/lib/python3.10/site-packages/dkr/core/webbing.py", line 41, in setup
    print(f"Using config property {KERI_CESR_CFG} to look for {KERI_CESR} files{data[KERI_CESR_CFG]}")
KeyError: 'keri.cesr.dir'
```
What would be the missing piece?

**Comment by 2byrds** [comment]
Hi @jruizaranguren 
I recommend you work from my dev branch. the GETTING_STARTED there will guide you through that configuration, etc https://github.com/2byrds/did-webs-resolver/tree/getting_started
I'm working on a bug in the resolver currently but for what you are doing it should be good.

**Comment by 2byrds** [comment]
Hi @jruizaranguren I have merged the branch to main. I will create issues for the resolver bugs that i continue to work on.

**Comment by jruizaranguren** [comment]
@2byrds , thanks for the update. The script now creates the files at new directory:

* ./{prefix}/did.json
* ./{prefix}]/keri.cesr

And then, running the service raises:

```
  File "/my/path/to/venv/lib/python3.10/site-packages/keri/db/dbing.py", line 448, in getVal
    with self.env.begin(db=db, write=False, buffers=True) as txn:
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument
```

The reliance of `keri` code in general on certain path structures is quite annoying, and It makes it quite difficult to consider it for production usages. I think users should be in full control on where store things (identifiers, logs, configurations, etc.).

**Comment by jruizaranguren** [comment]
> Then getting into production would be the next priority and i'm happy to work with you to adjust. 

Sure, even source of problems comes from `keripy` and its coupling to a certain directory structure and defaults.
