### ISSUE TITLE
Apple M1-3 warning and precautions

### ISSUE THREAD

**Issue by henkvancann** [hyperledger-labs/did-webs-resolver#45]
When I follow the getting started and get to
```
docker compose up -d
```
I get back
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

This brings me to the [M1 trouble shooting section](https://github.com/hyperledger-labs/did-webs-resolver/blob/main/GETTING_STARTED.md#if-you-are-using-an-apple-silicon-m1-mac-then-you-might-need-to), that says:
"
In Docker, select `Use Rosetta for x86/amd64 emulation on Apple Silicon`
"

My Question / issue : What do you exactly mean with "in Docker" and where to "use Rosseta..."

**Comment by 2byrds** [comment]
> When I follow the getting started and get to
> 
> ```
> docker compose up -d
> ```
> 
> I get back `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
> 
> This brings me to the [M1 trouble shooting section](https://github.com/hyperledger-labs/did-webs-resolver/blob/main/GETTING_STARTED.md#if-you-are-using-an-apple-silicon-m1-mac-then-you-might-need-to), that says: " In Docker, select `Use Rosetta for x86/amd64 emulation on Apple Silicon` "
> 
> My Question / issue : What do you exactly mean with "in Docker" and where to "use Rosseta..."

When using docker on a MAC, usually you will have the Docker Desktop app for managing your docker so using the gear icon you can make the selection like this:
<img width="1351" alt="image" src="https://github.com/hyperledger-labs/did-webs-resolver/assets/681493/6c8a79ec-0218-45f5-a110-461f48a086c8">
